export const blogList = [
    {
      id: 1,
      title: 'Introducción a la Computación Distribuida',
      category: 'Computación Distribuida',
      subCategory: ['Arquitectura', 'Fundamentos', 'Introducción'],
      description:
        "La computación distribuida es un modelo para resolver problemas de computación masiva utilizando un gran número de ordenadores organizados en clústeres incrustados en una infraestructura de telecomunicaciones distribuida.",
      authorName: 'RICARDO TURRIAGO',
      authorAvatar: '/assets/images/turriago.jpg',
      createdAt: '3 de junio/2022',
      cover: '/assets/images/apps1.jpg',
    },
    {
      id: 2,
      title: 'Paradigmas de las Aplicaciones Distribuidas',
      category: 'Paradigmas',
      subCategory: ['Paralelo', 'Aplicaciones', 'Sistema'],
      description:
        "Un paradigma de programación es una manera o estilo de programación de software. Existen diferentes formas de diseñar un lenguaje de programación y varios modos de trabajar para obtener los resultados que necesitan los programadores. En las aplicaciones distribuidas, existen los paradigmas 'Sistema de Colas de Mensaje', los llamados 'Agentes Móviles', los 'Servicios de red' y el 'Espacio de objeto'.",
      authorName: 'PAOLA ZAMBRANO',
      authorAvatar: '/assets/images/paola.jpeg',
      createdAt: '3 de junio/2022',
      cover: '/assets/images/apps2.png',
    },
    {
      id: 3,
      title: 'El Protocolo TCP/IP',
      category: 'Cliente/Servidor',
      subCategory: ['Protocolo', 'Modelos', 'Lógica'],
      description:
        "Los protocolos son conjuntos de normas para formatos de mensaje y procedimientos que permiten a las máquinas y los programas de aplicación intercambiar información. Cada máquina implicada en la comunicación debe seguir estas normas para que el sistema principal de recepción pueda interpretar el mensaje. El conjunto de protocolos TCP/IP puede interpretarse en términos de capas (o niveles). Esta figura muestra las capas del protocolo TCP/IP. Empezando por la parte superior son: capa de aplicación, capa de transporte, capa de red, capa de interfaz de red y hardware.",
      authorName: 'LIN SALINAS',
      authorAvatar: '/assets/images/salinas.jpeg',
      createdAt: '14 de junio/2022',
      cover: '/assets/images/apps3.jpg',
    },
    {
      id: 4,
      title: 'La Red, el Cliente y el Servidor',
      category: 'Cliente/Servidor',
      subCategory: ['Informática', 'Multicapa', 'Arquitectura'],
      description:
        "En las redes estructuradas bajo el modelo cliente servidor, los clientes centralizan diferentes aplicaciones y recursos en el servidor. El servidor, a su vez, se encarga de que estos recursos estén disponibles cada vez que un cliente los requiere.",
      authorName: 'LIN SALINAS',
      authorAvatar: '/assets/images/salinas.jpeg',
      createdAt: '14 de junio/2022',
      cover: '/assets/images/apps4.png',
    },
    {
      id: 5,
      title: 'El Protocolo UDP',
      category: 'Protocolos',
      subCategory: ['Modelos', 'Lógica', 'Datagramas'],
      description:
        "El protocolo UDP (Datagramas de usuario), es aquel que permite la transmisión de información sin conexión de los datagramas que están basados en protocolos IP, si bien este protocolo no es conocido como el TCP/IP, se clasifica en el nivel de transporte y, en consecuencia, se encuentra en una capa intermedia entre la capa de red y la capa de aplicación.",
      authorName: 'RICARDO TURRIAGO',
      authorAvatar: '/assets/images/turriago.jpg',
      createdAt: '14 de junio/2022',
      cover: '/assets/images/apps5.jpg',
    },
    {
      id: 6,
      title: 'Los Sockets (Java)',
      category: 'Java',
      subCategory: ['Comunicación', 'Flujos', 'Streams'],
      description:
        "Los Sockets son puntos finales de enlaces de comunicaciones entre procesos. Los procesos los tratan como descriptores de ficheros, de forma que se pueden intercambiar datos con otros procesos transmitiendo y recibiendo a través de sockets. El tipo de sockets describe la forma en la que se transfiere información a través de ese socket.",
      authorName: 'RICARDO TURRIAGO',
      authorAvatar: '/assets/images/turriago.jpg',
      createdAt: '14 de junio/2022',
      cover: '/assets/images/apps6.jpg',
    },
    {
      id: 7,
      title: 'Los Web Sockets (Java)',
      category: 'Java',
      subCategory: ['Comunicación', 'Flujos', 'Streams'],
      description:
        "Para entender los Web Sockets, son considerados como una conexión bidireccional punto a punto entre un navegador y su servidor, de tal manera que ambas partes se puedan enviar mensajes. Para la parte del cliente no resulta ninguna innovación pero para la parte del servidor sí ya que permite enviar información al cliente sin obligar a este a realizar peticiones AJAX cada x segundos.",
      authorName: 'PAOLA ZAMBRANO',
      authorAvatar: '/assets/images/paola.jpeg',
      createdAt: '21 de junio/2022',
      cover: '/assets/images/apps7.jpg',
    },
    {
      id: 8,
      title: 'Los Web Sockets (Java)',
      category: 'Java',
      subCategory: ['Comunicación', 'Flujos', 'Streams'],
      description:
        "Para entender los Web Sockets, son considerados como una conexión bidireccional punto a punto entre un navegador y su servidor, de tal manera que ambas partes se puedan enviar mensajes. Para la parte del cliente no resulta ninguna innovación pero para la parte del servidor sí ya que permite enviar información al cliente sin obligar a este a realizar peticiones AJAX cada x segundos.",
      authorName: 'PAOLA ZAMBRANO',
      authorAvatar: '/assets/images/paola.jpeg',
      createdAt: '21 de junio/2022',
      cover: '/assets/images/apps7.jpg',
    },
    {
      id: 9,
      title: 'Los Web Sockets (Java)',
      category: 'Java',
      subCategory: ['Comunicación', 'Flujos', 'Streams'],
      description:
        "Para entender los Web Sockets, son considerados como una conexión bidireccional punto a punto entre un navegador y su servidor, de tal manera que ambas partes se puedan enviar mensajes. Para la parte del cliente no resulta ninguna innovación pero para la parte del servidor sí ya que permite enviar información al cliente sin obligar a este a realizar peticiones AJAX cada x segundos.",
      authorName: 'PAOLA ZAMBRANO',
      authorAvatar: '/assets/images/paola.jpeg',
      createdAt: '21 de junio/2022',
      cover: '/assets/images/apps7.jpg',
    },
    {
      id: 10,
      title: 'Los Web Sockets (Java)',
      category: 'Java',
      subCategory: ['Comunicación', 'Flujos', 'Streams'],
      description:
        "Para entender los Web Sockets, son considerados como una conexión bidireccional punto a punto entre un navegador y su servidor, de tal manera que ambas partes se puedan enviar mensajes. Para la parte del cliente no resulta ninguna innovación pero para la parte del servidor sí ya que permite enviar información al cliente sin obligar a este a realizar peticiones AJAX cada x segundos.",
      description2: "Detalle completo",
        authorName: 'PAOLA ZAMBRANO',
      authorAvatar: '/assets/images/paola.jpeg',
      createdAt: '21 de junio/2022',
      cover: 'url cover',
      refer: ['google.com', 'Flujos', 'Streams'],
      imgs: ['url imágenes del post', '', ''],
    },
  ];
  